version: '3.8'

services:
  web:
    platform: linux/arm64
    build:
      context: .
      target: web-dev
    volumes:
      - .:/app # Map entire project to allow writing secrets.h and running pio
      - /app/web/node_modules
      - /app/web/.next
      # Map the build output folder for access to all binaries
      - ./.pio/build:/app/web/public/build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - PROJECT_ROOT=/app
